# Generated by Django 3.1.3 on 2020-11-20 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20201120_2335'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='post_snippet',
            field=models.CharField(default='The is a snippet of word the should be rendered at the home page of this blog page.', max_length=455),
        ),
    ]
