# Generated by Django 3.1.3 on 2020-11-20 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_post_post_snippet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='post_snippet',
            field=models.CharField(default='The is a snippet of word the should be rendered at the home page of this blog page.', max_length=200),
        ),
    ]
